<?xml version="1.0"?>
<!-- Refactored by Arn-O -->

<robot name="youbot" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

  <!-- includes -->
  <xacro:include filename="$(find youbot_description)/urdf/youbot_base/specs.urdf.xacro" />
  <xacro:include filename="$(find youbot_description)/urdf/youbot_base/base.gazebo.xacro" />

  <xacro:macro name="youbot_base">

    <!-- ### links ### -->
    <!-- base -->
    <link name="base_link">
      <inertial>
        <mass value="${base_mass}" />
        <origin xyz="${base_pose_x} ${base_pose_y} ${base_pose_z}" />
        <inertia ixx="1.000" ixy="0.000" ixz="0.000" iyy="1.000" iyz="0.000" izz="1.000" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />  
        <geometry>
          <mesh filename="package://youbot_description/meshes/youbot_base/base_frame.dae"/>
        </geometry> 
      </visual>
    </link>

    <!-- wheels -->
    <!-- front left wheel -->
    <link name="wheel_link_fl">
      <inertial>
        <mass value="${wheel_mass}" />
        <inertia  ixx="0.010" ixy="0.000" ixz="0.000" iyy="0.010" iyz="0.000" izz="0.010" />
      </inertial>

      <visual>
        <geometry>
          <sphere radius="${wheel_radius}" />
        </geometry>
      </visual>

      <collision>
        <geometry>
          <sphere radius="${wheel_radius}" />
        </geometry>
      </collision>
    </link>

    <!-- ### joints ### -->
    <joint name="wheel_fl_joint" type="fixed">
      <origin xyz="${wheel_fl_pose_x} ${wheel_fl_pose_y} ${wheel_fl_pose_z}" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="wheel_link_fl" />
    </joint>

    <xacro:youbot_base_gazebo />

  </xacro:macro>

</robot>

<!--
    <link name="${name}_footprint">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <link name="${name}_link">
      <inertial>
        <mass value="${base_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423" iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />  
        <geometry>
          <mesh filename="package://youbot_description/meshes/youbot_base/base.dae"/>
        </geometry> 
      </visual>
    </link>	

    <front left wheel >	
    <link name="wheel_link_fl">
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://youbot_description/meshes/youbot_base/front-left_wheel.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_radius}" />
        </geometry>
      </collision>
    </link>

    <front right wheel >
    <link name="wheel_link_fr">
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://youbot_description/meshes/youbot_base/front-right_wheel.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_radius}" />
        </geometry>
      </collision>
    </link>

    <back left wheel  >
    <link name="wheel_link_bl">
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://youbot_description/meshes/youbot_base/back-left_wheel.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_radius}" />
        </geometry>
      </collision>
    </link>

    < back right wheel  >
    <link name="wheel_link_br">
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://youbot_description/meshes/youbot_base/back-right_wheel.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_radius}" />
        </geometry>
      </collision>
    </link>

    < ### joints ### >
    <joint name="${name}_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <child link="${name}_link" />
      <parent link="${name}_footprint"/>
    </joint>

	-->

    <!-- extensions -->

